// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package button

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"

const (
	buttonBaseClass = "inline-flex items-center justify-center text-sm font-medium " +
		"transition-colors focus:outline-none disabled:pointer-events-none disabled:opacity-50"
)

var buttonVariantClasses = map[string]string{
	"default":     "bg-primary text-on-primary hover:opacity-90 border border-outline",
	"destructive": "bg-danger text-on-danger hover:opacity-90 border border-outline",
	"outline":     "border border-outline bg-surface hover:bg-surface-alt text-on-surface",
	"secondary":   "bg-secondary text-on-secondary hover:opacity-80 border border-outline",
	"ghost":       "hover:bg-surface-alt text-on-surface",
	"link":        "text-primary underline-offset-4 hover:underline",
}

var buttonSizeClasses = map[string]string{
	"default": "h-10 px-4 py-2 rounded-[var(--radius-radius)]",
	"sm":      "h-9 px-3 rounded-[var(--radius-radius)]",
	"lg":      "h-11 px-8 rounded-[var(--radius-radius)]",
	"icon":    "h-10 w-10 rounded-[var(--radius-radius)]",
}

type ButtonProps struct {
	Variant string
	Size    string
	Class   string
	Extra   templ.Attributes
}

func buildButtonClass(props *ButtonProps) string {
	if props == nil {
		props = &ButtonProps{}
	}
	if props.Variant == "" {
		props.Variant = "default"
	}
	if props.Size == "" {
		props.Size = "default"
	}

	return fmt.Sprintf("%s %s %s %s",
		buttonBaseClass,
		buttonVariantClasses[props.Variant],
		buttonSizeClasses[props.Size],
		props.Class)
}

func New(props *ButtonProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if props == nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "props = &ButtonProps ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		var templ_7745c5c3_Var2 = []any{buildButtonClass(props)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<button class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/primitives/button/button.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, props.Extra)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, ">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
