// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package flex

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"strings"
)

type Direction string

const (
	Row    Direction = "row"
	Column Direction = "column"
)

type FlexProps struct {
	// Breakpoint directions
	Default Direction // base (no prefix)
	SM      Direction // sm:
	MD      Direction // md:
	LG      Direction // lg:
	XL      Direction // xl:
	XXL     Direction // 2xl:

	Class string
	Extra templ.Attributes
}

func buildFlexClass(props *FlexProps) string {
	if props == nil {
		props = &FlexProps{}
	}

	var classes []string
	classes = append(classes, "flex")

	// Build responsive classes with cascading logic
	directions := map[string]Direction{
		"":     props.Default,
		"sm:":  props.SM,
		"md:":  props.MD,
		"lg:":  props.LG,
		"xl:":  props.XL,
		"2xl:": props.XXL,
	}

	// Track the current direction for cascading
	currentDirection := props.Default
	if currentDirection == "" {
		currentDirection = Row // Default to row if nothing specified
	}

	// Add base direction
	if currentDirection == Column {
		classes = append(classes, "flex-col")
	} else {
		classes = append(classes, "flex-row")
	}

	// Add responsive classes
	breakpoints := []string{"sm:", "md:", "lg:", "xl:", "2xl:"}
	for _, bp := range breakpoints {
		if directions[bp] != "" {
			currentDirection = directions[bp]
		}

		// Only add class if it's different from the previous breakpoint
		if directions[bp] != "" {
			if currentDirection == Column {
				classes = append(classes, bp+"flex-col")
			} else {
				classes = append(classes, bp+"flex-row")
			}
		}
	}

	// Add custom class if provided
	if props.Class != "" {
		classes = append(classes, props.Class)
	}

	return strings.Join(classes, " ")
}

func New(props *FlexProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if props == nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "props = &FlexProps")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		var templ_7745c5c3_Var2 = []any{buildFlexClass(props)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/primitives/flex/flex.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, props.Extra)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, ">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
