// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package box

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"

const (
	boxBaseClass = "w-full bg-surface text-on-surface"
)

var boxVariantClasses = map[string]string{
	"default":   "shadow-sm rounded-[var(--radius-radius)]",
	"soft":      "shadow-sm bg-surface-alt rounded-[var(--radius-radius)]",
	"floating":  "shadow-lg rounded-[var(--radius-radius)]",
	"elevated":  "shadow-xl border-2 border-outline-strong rounded-[var(--radius-radius)]",
	"flat":      "shadow-none rounded-[var(--radius-radius)]",
	"container": "shadow-none",
}

var boxPaddingClasses = map[string]string{
	"none": "",
	"sm":   "p-3",
	"md":   "p-4",
	"lg":   "p-6",
	"xl":   "p-8",
}

var boxSizeClasses = map[string]string{
	"default": "max-w-7xl",
	"sm":      "max-w-sm",
	"md":      "max-w-md",
	"lg":      "max-w-lg",
	"xl":      "max-w-xl",
	"2xl":     "max-w-2xl",
	"3xl":     "max-w-3xl",
	"4xl":     "max-w-4xl",
	"5xl":     "max-w-5xl",
	"6xl":     "max-w-6xl",
}

type BoxProps struct {
	Variant string
	Size    string
	Padding string
	Border  bool
	Class   string
	Extra   templ.Attributes
}

func buildBoxClass(props *BoxProps) string {
	if props == nil {
		props = &BoxProps{}
	}
	if props.Variant == "" {
		props.Variant = "default"
	}
	if props.Size == "" {
		props.Size = "default"
	}
	if props.Padding == "" {
		props.Padding = "none"
	}

	borderClass := ""
	if props.Border {
		borderClass = "border border-outline"
	}

	return fmt.Sprintf("%s %s %s %s %s %s",
		boxBaseClass,
		borderClass,
		boxVariantClasses[props.Variant],
		boxSizeClasses[props.Size],
		boxPaddingClasses[props.Padding],
		props.Class)
}

func New(props *BoxProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if props == nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "props = &BoxProps")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		var templ_7745c5c3_Var2 = []any{buildBoxClass(props)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/primitives/box/box.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, props.Extra)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, ">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
