// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package themeswitcher

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "portfolioed/ui/primitives/dropdown"

type ThemeSwitcherProps struct {
	Class string
	Extra templ.Attributes
}

func getThemeOptions() []dropdown.Option {
	return []dropdown.Option{
		{Value: "minimal", Label: "Minimal"},
		{Value: "arctic", Label: "Arctic"},
		{Value: "modern", Label: "Modern"},
		{Value: "high-contrast", Label: "High Contrast"},
		{Value: "neo-brutalism", Label: "Neo Brutalism"},
		{Value: "halloween", Label: "Halloween"},
		{Value: "zombie", Label: "Zombie"},
		{Value: "pastel", Label: "Pastel"},
		{Value: "90s", Label: "90s"},
		{Value: "christmas", Label: "Christmas"},
		{Value: "prototype", Label: "Prototype"},
		{Value: "news", Label: "News"},
		{Value: "industrial", Label: "Industrial"},
	}
}

func New(props *ThemeSwitcherProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if props == nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "props = &ThemeSwitcherProps")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		var templ_7745c5c3_Var2 = []any{props.Class}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div x-data=\"{\n\t\tinit() {\n\t\t\tconst savedTheme = localStorage.getItem('theme') || 'minimal';\n\t\t\tdocument.body.setAttribute('data-theme', savedTheme);\n\t\t}\n\t}\" x-on:dropdown-change=\"\n\t\tconsole.log('Theme changed to:', $event.detail.option.value);\n\t\tdocument.body.setAttribute('data-theme', $event.detail.option.value);\n\t\tlocalStorage.setItem('theme', $event.detail.option.value);\n\t\" class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/primitives/theme-switcher/theme-switcher.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, props.Extra)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, ">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = dropdown.New(&dropdown.DropdownProps{
			Options:      getThemeOptions(),
			Placeholder:  "Minimal",
			Name:         "theme",
			InitialValue: "minimal",
			Class:        "max-w-none w-auto",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
